title: "BEND0US | Offensive Security Notes"
description: "Research and insights on Red Teaming, Web Security, Active Directory, Cloud, and vulnerability exploitation."
theme: minima
author:
  name: "BEND0US"
baseurl: ""
url: "https://bend0us.github.io"
show_excerpts: true
markdown: kramdown

header_pages:
  - index.md
  - red-team.md
  - web-security.md
  - active-directory-hacking.md
  - cloud-and-container-hacking.md
  - binary-exploitation.md
  - vulnerabilities.md
